---
title: "Untitled"
output: github_document
author: "Almo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{bash eval=FALSE}
folder="/Users/ascarpa/Downloads/invadego_simulations/Paramutagenic_chain_reaction/Invasion_clusters"
tool="/Users/ascarpa/invade-invadego/invadego021"
mkdir $folder



$tool --N 1000 --gen 5000 --genome mb:10,10,10,10,10 --cluster kb:300,300,300,300,300 --rr 4,4,4,4,4 --rep 100 --steps 20 -u 0.1 --basepop 100 --sampleid p00 > $folder/p0 &
$tool --N 1000 --gen 5000 --genome mb:10,10,10,10,10 --cluster kb:300,300,300,300,300 --rr 4,4,4,4,4 --rep 100 --steps 20 -u 0.1 --basepop 100 --paramutation 100:1 --sampleid p50 > $folder/p1 &
$tool --N 1000 --gen 5000 --genome mb:10,10,10,10,10 --cluster kb:300,300,300,300,300 --rr 4,4,4,4,4 --rep 100 --steps 20 -u 0.1 --basepop 100 --paramutation 10:0 --sampleid p10 > $folder/p10 &
$tool --N 1000 --gen 5000 --genome mb:10,10,10,10,10 --cluster kb:300,300,300,300,300 --rr 4,4,4,4,4 --rep 100 --steps 20 -u 0.1 --basepop 100 --paramutation 1:0 --sampleid p100 > $folder/p100
```
## merge

```{bash}
cat p* |grep -v "^Invade"|grep -v "^#" > data-for.r
```

## Setting the environment
``` {r}
library(tidyverse)
```

# Invasion dynamics

## Average TE copy numbers

